// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEUCT6qQmrMnS_Sxl3MqcPvpNwQc7Sp8',
    appId: '1:988320155539:web:e7c5d251ce1534f1654a66',
    messagingSenderId: '988320155539',
    projectId: 'daftar-afandi',
    authDomain: 'daftar-afandi.firebaseapp.com',
    storageBucket: 'daftar-afandi.firebasestorage.app',
    measurementId: 'G-YM11YE03BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCddacn1NlDAkkEnRZ-qrsT_7m9VVcaLCk',
    appId: '1:988320155539:android:5bf15b72ccb6fb8f654a66',
    messagingSenderId: '988320155539',
    projectId: 'daftar-afandi',
    storageBucket: 'daftar-afandi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0tWaXRmaYEtQuozF-SHEkLFqLPve9f_A',
    appId: '1:988320155539:ios:f1b40ab1cf5e515b654a66',
    messagingSenderId: '988320155539',
    projectId: 'daftar-afandi',
    storageBucket: 'daftar-afandi.firebasestorage.app',
    iosBundleId: 'com.example.daftarAfandiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0tWaXRmaYEtQuozF-SHEkLFqLPve9f_A',
    appId: '1:988320155539:ios:f1b40ab1cf5e515b654a66',
    messagingSenderId: '988320155539',
    projectId: 'daftar-afandi',
    storageBucket: 'daftar-afandi.firebasestorage.app',
    iosBundleId: 'com.example.daftarAfandiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnEUCT6qQmrMnS_Sxl3MqcPvpNwQc7Sp8',
    appId: '1:988320155539:web:579c1ec632854c4d654a66',
    messagingSenderId: '988320155539',
    projectId: 'daftar-afandi',
    authDomain: 'daftar-afandi.firebaseapp.com',
    storageBucket: 'daftar-afandi.firebasestorage.app',
    measurementId: 'G-PHDPF74KPY',
  );

}